name: Sync to Daily Report Hub
on:
  push:
    branches: [main, master]
  pull_request:
    types: [merged]

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 差分取得用
      
      - name: Get repository info and diff
        run: |
          # リポジトリ名を取得
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          
          # 差分情報を取得
          git diff HEAD~1 --name-status > diff.txt || echo "No diff available" > diff.txt
          git log -1 --pretty=format:"%h %s %an %ad" --date=short > commit.txt
          
          # 現在時刻を追加
          echo "Updated: $(date '+%Y-%m-%d %H:%M:%S')" > update_time.txt
      
      - name: Clone and update report hub
        env:
          GITHUB_TOKEN: ${{ secrets.REPORT_TOKEN }}
        run: |
          # Git設定を先に行う
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # daily-report-hubをクローン（認証情報を含むURL）
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/Sunwood-ai-labs/daily-report-hub.git
          
          # プロジェクトディレクトリを作成
          mkdir -p daily-report-hub/projects/$REPO_NAME
          
          # ファイルをコピー
          cp README.md daily-report-hub/projects/$REPO_NAME/ 2>/dev/null || echo "# $REPO_NAME" > daily-report-hub/projects/$REPO_NAME/README.md
          cp diff.txt daily-report-hub/projects/$REPO_NAME/
          cp commit.txt daily-report-hub/projects/$REPO_NAME/
          cp update_time.txt daily-report-hub/projects/$REPO_NAME/
          
          # メタデータファイルを作成
          cat > daily-report-hub/projects/$REPO_NAME/metadata.json << EOF
          {
            "repository": "$GITHUB_REPOSITORY",
            "branch": "$GITHUB_REF_NAME",
            "commit_sha": "$GITHUB_SHA",
            "updated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "workflow_run": "$GITHUB_RUN_ID"
          }
          EOF
          
          # 変更をコミット・プッシュ
          cd daily-report-hub
          git add .
          
          # 変更があるかチェック
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update from $GITHUB_REPOSITORY - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi